// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxFWlBv7JlVsKgikiGs_QHAULbcDp9egk',
    appId: '1:1027537164454:web:ed5a05351c579571ca7c67',
    messagingSenderId: '1027537164454',
    projectId: 'work-flow-management-system',
    authDomain: 'work-flow-management-system.firebaseapp.com',
    storageBucket: 'work-flow-management-system.appspot.com',
    measurementId: 'G-C7X3QV4HXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL8YZkRVc_evzX4OsF8CFzCPM8rvZpSok',
    appId: '1:1027537164454:android:982b921a2001d432ca7c67',
    messagingSenderId: '1027537164454',
    projectId: 'work-flow-management-system',
    storageBucket: 'work-flow-management-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcUenZkL97T8J-eU5jpHqmOkR3JMTyHOc',
    appId: '1:1027537164454:ios:ad4f9291b814b993ca7c67',
    messagingSenderId: '1027537164454',
    projectId: 'work-flow-management-system',
    storageBucket: 'work-flow-management-system.appspot.com',
    iosBundleId: 'com.example.workfowManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcUenZkL97T8J-eU5jpHqmOkR3JMTyHOc',
    appId: '1:1027537164454:ios:506123a22f31777aca7c67',
    messagingSenderId: '1027537164454',
    projectId: 'work-flow-management-system',
    storageBucket: 'work-flow-management-system.appspot.com',
    iosBundleId: 'com.example.workfowManagementSystem.RunnerTests',
  );
}
